export interface DirectorItem {
  id: string;
  name: string;
  lastName: string;
  letter: string;
  tmdbId?: number;
  photoUrl: string;
  bio: string;
  style: string;
  nationality: string;
  birthYear: string;
}

export const DIRECTORS_DATABASE: DirectorItem[] = [
  // A
  {
    id: 'chantal-akerman',
    name: 'Chantal Akerman',
    lastName: 'Akerman',
    letter: 'A',
    tmdbId: 78589,
    photoUrl: 'https://image.tmdb.org/t/p/w500/8d88cQ8m721lZJzV2J5iVzZ5XyZ.jpg',
    bio: 'Pioniera radicale del cinema strutturalista e femminista, maestra della temporalità reale.',
    style: 'Inquadrature fisse, tempo dilatato, ritualità quotidiana.',
    nationality: 'Belgio',
    birthYear: '1950',
  },
  {
    id: 'woody-allen',
    name: 'Woody Allen',
    lastName: 'Allen',
    letter: 'A',
    tmdbId: 1243,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'Icona della commedia nevrotica e del dramma esistenziale newyorkese.',
    style: 'Dialoghi brillanti, jazz, piani sequenza colloquiali.',
    nationality: 'USA',
    birthYear: '1935',
  },
  {
    id: 'pedro-almodovar',
    name: 'Pedro Almodóvar',
    lastName: 'Almodóvar',
    letter: 'A',
    tmdbId: 444,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Autore spagnolo dal cromatismo vibrante e melodramma trasgressivo.',
    style: 'Colori primari saturi, passione melodrammatica, estetica kitsch-chic.',
    nationality: 'Spagna',
    birthYear: '1949',
  },
  {
    id: 'paul-thomas-anderson',
    name: 'Paul Thomas Anderson',
    lastName: 'Anderson',
    letter: 'A',
    tmdbId: 2710,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Uno dei più grandi virtuosi della cinepresa e del dramma corale americano.',
    style: 'Carrellate fluide, ritratti psicologici ossessivi, 35mm caldo.',
    nationality: 'USA',
    birthYear: '1970',
  },
  {
    id: 'wes-anderson',
    name: 'Wes Anderson',
    lastName: 'Anderson',
    letter: 'A',
    tmdbId: 5655,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'Architetto della simmetria maniacale e delle palette pastello.',
    style: 'Simmetria frontale, palette pastello, stop-motion e ironia naif.',
    nationality: 'USA',
    birthYear: '1969',
  },
  {
    id: 'michelangelo-antonioni',
    name: 'Michelangelo Antonioni',
    lastName: 'Antonioni',
    letter: 'A',
    tmdbId: 4208,
    photoUrl: 'https://image.tmdb.org/t/p/w500/n5p6tQ6p1kY3mN0hV4jZ5Xk1jZ2.jpg',
    bio: 'Poeta visivo dell\'incomunicabilità e del paesaggio metafisico.',
    style: 'Tempi morti, architettura modernista, alienazione borghese.',
    nationality: 'Italia',
    birthYear: '1912',
  },
  {
    id: 'darren-aronofsky',
    name: 'Darren Aronofsky',
    lastName: 'Aronofsky',
    letter: 'A',
    tmdbId: 282,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Esploratore delle ossessioni autodistruttive e del body horror psicologico.',
    style: 'Montaggio frenetico hip-hop, SnorriCam, allucinazione claustrofobica.',
    nationality: 'USA',
    birthYear: '1969',
  },
  {
    id: 'ari-aster',
    name: 'Ari Aster',
    lastName: 'Aster',
    letter: 'A',
    tmdbId: 2026138,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Maestro dell\'elevated horror contemporaneo e del trauma generazionale.',
    style: 'Luce solare inquietante, rigore formale geometrico, shock visivo.',
    nationality: 'USA',
    birthYear: '1986',
  },

  // B
  {
    id: 'ingmar-bergman',
    name: 'Ingmar Bergman',
    lastName: 'Bergman',
    letter: 'B',
    tmdbId: 1047,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Il più profondo scandagliatore dell\'anima, della fede e della mortalità umana.',
    style: 'Primissimi piani scultorei, silenzio metafisico, bianco e nero tagliente.',
    nationality: 'Svezia',
    birthYear: '1918',
  },
  {
    id: 'bernardo-bertolucci',
    name: 'Bernardo Bertolucci',
    lastName: 'Bertolucci',
    letter: 'B',
    tmdbId: 301,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Maestro della sensualità visiva, della politica e dell\'epica intimista.',
    style: 'Carrellate barocche, fotografia calda di Storaro, lirismo decadente.',
    nationality: 'Italia',
    birthYear: '1940',
  },
  {
    id: 'kathryn-bigelow',
    name: 'Kathryn Bigelow',
    lastName: 'Bigelow',
    letter: 'B',
    tmdbId: 13344,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'Prima donna a vincere l\'Oscar alla regia, regista di pura adrenalina tattile.',
    style: 'Regia immersiva, montaggio ad alto impatto, tensione cinetica.',
    nationality: 'USA',
    birthYear: '1951',
  },
  {
    id: 'bong-joon-ho',
    name: 'Bong Joon-ho',
    lastName: 'Bong',
    letter: 'B',
    tmdbId: 21684,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Auteur coreano premio Oscar, genio della satira sociale e dei cambi di tono.',
    style: 'Precisione architettonica, umorismo amaro, fluidità narrativa magistrale.',
    nationality: 'Corea del Sud',
    birthYear: '1969',
  },
  {
    id: 'tim-burton',
    name: 'Tim Burton',
    lastName: 'Burton',
    letter: 'B',
    tmdbId: 510,
    photoUrl: 'https://image.tmdb.org/t/p/w500/zvhkg1N3T9w3t3X1a9W9g8bL5Jb.jpg',
    bio: 'Visionario del gotico fiabesco e paladino dei freak emarginati.',
    style: 'Espressionismo gotico, righe bianche e nere, poesia dell\'assurdo.',
    nationality: 'USA',
    birthYear: '1958',
  },

  // C
  {
    id: 'james-cameron',
    name: 'James Cameron',
    lastName: 'Cameron',
    letter: 'C',
    tmdbId: 2710,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Il demiurgo del cinema spettacolare e dell\'innovazione tecnologica planetaria.',
    style: 'World-building titanico, ritmo narrativo inesorabile, biomeccanica.',
    nationality: 'Canada',
    birthYear: '1954',
  },
  {
    id: 'john-carpenter',
    name: 'John Carpenter',
    lastName: 'Carpenter',
    letter: 'C',
    tmdbId: 4430,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Il maestro indiscusso dell\'horror minimalista e dell\'anamorfico Panavision.',
    style: 'Panavision 2.39:1, sintetizzatori minimali ipnotici, tensione pura.',
    nationality: 'USA',
    birthYear: '1948',
  },
  {
    id: 'damien-chazelle',
    name: 'Damien Chazelle',
    lastName: 'Chazelle',
    letter: 'C',
    tmdbId: 135898,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Il più giovane vincitore dell\'Oscar alla regia, cantore dell\'ossessione ritmica.',
    style: 'Montaggio sinfonico, swing cinetico, colori primari saturi.',
    nationality: 'USA',
    birthYear: '1985',
  },
  {
    id: 'coen-brothers',
    name: 'Joel & Ethan Coen',
    lastName: 'Coen',
    letter: 'C',
    tmdbId: 1223,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'I maestri del noir nichilista, del fatalismo beffardo e della satira americana.',
    style: 'Grandangoli deformanti, dialoghi millimetrici, cinismo poetico.',
    nationality: 'USA',
    birthYear: '1954',
  },
  {
    id: 'francis-ford-coppola',
    name: 'Francis Ford Coppola',
    lastName: 'Coppola',
    letter: 'C',
    tmdbId: 1776,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Uno dei padri fondatori della New Hollywood e della monumentalità cinematografica.',
    style: 'Chiaroscuro operistico, montaggio parallelo maestoso, tragedia shakespeariana.',
    nationality: 'USA',
    birthYear: '1939',
  },
  {
    id: 'david-cronenberg',
    name: 'David Cronenberg',
    lastName: 'Cronenberg',
    letter: 'C',
    tmdbId: 224,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Profeta indiscusso del body horror e della fusione tra carne e tecnologia.',
    style: 'Mutazione organica, freddezza clinica, estetica viscerale.',
    nationality: 'Canada',
    birthYear: '1943',
  },
  {
    id: 'alfonso-cuaron',
    name: 'Alfonso Cuarón',
    lastName: 'Cuarón',
    letter: 'C',
    tmdbId: 11218,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Virtuoso assoluto del piano sequenza e del realismo immersivo.',
    style: 'Piani sequenza interminabili, profondità di campo estesa, fotografia naturale.',
    nationality: 'Messico',
    birthYear: '1961',
  },

  // D
  {
    id: 'brian-de-palma',
    name: 'Brian De Palma',
    lastName: 'De Palma',
    letter: 'D',
    tmdbId: 2226,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Il più grande discepolo barocco di Hitchcock, maestro dello split-screen.',
    style: 'Split-screen, lenti bifocali, carrelli circolari a 360°, voyeurismo.',
    nationality: 'USA',
    birthYear: '1940',
  },
  {
    id: 'xavier-dolan',
    name: 'Xavier Dolan',
    lastName: 'Dolan',
    letter: 'D',
    tmdbId: 128919,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'Enfant prodige quebecchese del cinema queer, del melodramma e dell\'emozione pop.',
    style: 'Rapporti d\'aspetto variabili (1:1), slow-motion musicale, costumi sgargianti.',
    nationality: 'Canada',
    birthYear: '1989',
  },

  // E
  {
    id: 'robert-eggers',
    name: 'Robert Eggers',
    lastName: 'Eggers',
    letter: 'E',
    tmdbId: 1475736,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Archeologo del folklore ancestrale, dell\'occulto e del terrore antropologico.',
    style: 'Luce naturale a candela, dialetti d\'epoca accurati, claustrofobia 1.19:1.',
    nationality: 'USA',
    birthYear: '1983',
  },
  {
    id: 'clint-eastwood',
    name: 'Clint Eastwood',
    lastName: 'Eastwood',
    letter: 'E',
    tmdbId: 190,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Leggenda vivente del cinema classico americano, erede morale di John Ford.',
    style: 'Regia essenziale, pochi ciak, chiaroscuri profondi, morale complessa.',
    nationality: 'USA',
    birthYear: '1930',
  },

  // F
  {
    id: 'federico-fellini',
    name: 'Federico Fellini',
    lastName: 'Fellini',
    letter: 'F',
    tmdbId: 4415,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Il più grande sognatore della storia del cinema, inventore del realismo onirico.',
    style: 'Onirismo circense, volti grotteschi, musiche di Nino Rota, barocco visionario.',
    nationality: 'Italia',
    birthYear: '1920',
  },
  {
    id: 'david-fincher',
    name: 'David Fincher',
    lastName: 'Fincher',
    letter: 'F',
    tmdbId: 7467,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Perfezionista maniacale del digitale e dell\'indagine sulla psiche criminale.',
    style: 'Movimenti di camera robotici, palette verde-ambra, 50+ ciak per scena.',
    nationality: 'USA',
    birthYear: '1962',
  },

  // G
  {
    id: 'greta-gerwig',
    name: 'Greta Gerwig',
    lastName: 'Gerwig',
    letter: 'G',
    tmdbId: 93874,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'Voce autoriale luminosa, capace di unire sensibilità indie e colossal pop.',
    style: 'Empatia travolgente, dialoghi sovrapposti, luce dorata naturale.',
    nationality: 'USA',
    birthYear: '1983',
  },
  {
    id: 'jean-luc-godard',
    name: 'Jean-Luc Godard',
    lastName: 'Godard',
    letter: 'G',
    tmdbId: 3776,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Il rivoluzionario supremo della Nouvelle Vague che ha reinventato il linguaggio del film.',
    style: 'Jump cut, rottura della quarta parete, saggismo politico e collage visivo.',
    nationality: 'Francia',
    birthYear: '1930',
  },
  {
    id: 'luca-guadagnino',
    name: 'Luca Guadagnino',
    lastName: 'Guadagnino',
    letter: 'G',
    tmdbId: 102434,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Maestro contemporaneo del cinema sensoriale, del desiderio e dell\'eleganza tattile.',
    style: 'Cinepresa sensuale, 35mm luminoso, montaggio ritmico ed estasi corporea.',
    nationality: 'Italia',
    birthYear: '1971',
  },

  // H
  {
    id: 'michael-haneke',
    name: 'Michael Haneke',
    lastName: 'Haneke',
    letter: 'H',
    tmdbId: 3609,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Chirurgo implacabile dell\'alienazione borghese e della violenza mediatica.',
    style: 'Piani fissi disturbanti, assenza di colonna sonora extradiegetica, rigore asettico.',
    nationality: 'Austria',
    birthYear: '1942',
  },
  {
    id: 'alfred-hitchcock',
    name: 'Alfred Hitchcock',
    lastName: 'Hitchcock',
    letter: 'H',
    tmdbId: 2636,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Il Maestro del Brivido e l\'architetto supremo della suspense visiva.',
    style: 'Montaggio puro, MacGuffin, dolly zoom (effetto Vertigo), controllo assoluto.',
    nationality: 'Regno Unito',
    birthYear: '1899',
  },

  // I
  {
    id: 'alejandro-inarritu',
    name: 'Alejandro G. Iñárritu',
    lastName: 'Iñárritu',
    letter: 'I',
    tmdbId: 2869,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Due volte premio Oscar, esploratore del dolore fisico e della continuità visiva.',
    style: 'Piani sequenza apparenti infiniti, grandangoli estremi, luce naturale di Lubezki.',
    nationality: 'Messico',
    birthYear: '1963',
  },

  // J
  {
    id: 'jim-jarmusch',
    name: 'Jim Jarmusch',
    lastName: 'Jarmusch',
    letter: 'J',
    tmdbId: 2450,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Il re del cinema indipendente americano minimalista, poetico e rilassato.',
    style: 'Ritmo dilatato, dissolvenze al nero, personaggi ai margini, musica ipnotica.',
    nationality: 'USA',
    birthYear: '1953',
  },
  {
    id: 'alejandro-jodorowsky',
    name: 'Alejandro Jodorowsky',
    lastName: 'Jodorowsky',
    letter: 'J',
    tmdbId: 9851,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Mistico, psicomago e creatore del cinema allucinatorio e spirituale più estremo.',
    style: 'Simbolismo alchemico, surrealismo sciamanico, provocazione sensoriale.',
    nationality: 'Cile',
    birthYear: '1929',
  },

  // K
  {
    id: 'stanley-kubrick',
    name: 'Stanley Kubrick',
    lastName: 'Kubrick',
    letter: 'K',
    tmdbId: 240,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'La mente più rigorosa e geometrica che abbia mai operato dietro la cinepresa.',
    style: 'Prospettiva centrale a un punto di fuga, carrellata inversa, rigore matematico.',
    nationality: 'USA',
    birthYear: '1928',
  },
  {
    id: 'akira-kurosawa',
    name: 'Akira Kurosawa',
    lastName: 'Kurosawa',
    letter: 'K',
    tmdbId: 5026,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'L\'Imperatore del cinema giapponese e pioniere del montaggio cinetico moderno.',
    style: 'Uso dinamico del meteo (pioggia/vento), teleobiettivi schiacciati, tagli in asse.',
    nationality: 'Giappone',
    birthYear: '1910',
  },
  {
    id: 'krzysztof-kieslowski',
    name: 'Krzysztof Kieślowski',
    lastName: 'Kieślowski',
    letter: 'K',
    tmdbId: 1146,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Il metafisico delle coincidenze umane e della trilogia dei colori.',
    style: 'Riflessi di luce su vetro, dettagli microscopici, musica diegetica di Preisner.',
    nationality: 'Polonia',
    birthYear: '1941',
  },

  // L
  {
    id: 'yorgos-lanthimos',
    name: 'Yorgos Lanthimos',
    lastName: 'Lanthimos',
    letter: 'L',
    tmdbId: 24968,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Architetto della Greek Weird Wave, dell\'assurdo satirico e del grandangolo estremo.',
    style: 'Obiettivi fisheye estremi, recitazione atona, zoom veloci e comicità grottesca.',
    nationality: 'Grecia',
    birthYear: '1973',
  },
  {
    id: 'sergio-leone',
    name: 'Sergio Leone',
    lastName: 'Leone',
    letter: 'L',
    tmdbId: 4385,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Il fondatore dello Spaghetti Western e maestro dell\'epica della dilatazione temporale.',
    style: 'Primissimi piani sugli occhi, campi lunghissimi, colonna sonora di Ennio Morricone.',
    nationality: 'Italia',
    birthYear: '1929',
  },
  {
    id: 'david-lynch',
    name: 'David Lynch',
    lastName: 'Lynch',
    letter: 'L',
    tmdbId: 5602,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Il maestro del subconscio, del surrealismo perturbante e del sound design tellurico.',
    style: 'Logiche oniriche non lineari, ronzii a bassa frequenza, tende rosse e mistero puro.',
    nationality: 'USA',
    birthYear: '1946',
  },

  // M
  {
    id: 'terrence-malick',
    name: 'Terrence Malick',
    lastName: 'Malick',
    letter: 'M',
    tmdbId: 1780,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Il filosofo visivo della luce dorata, della natura cosmica e del monologo interiore.',
    style: 'Luce della "magic hour", camera a mano fluttuante, montaggio associativo poetico.',
    nationality: 'USA',
    birthYear: '1943',
  },
  {
    id: 'michael-mann',
    name: 'Michael Mann',
    lastName: 'Mann',
    letter: 'M',
    tmdbId: 1133,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Il supremo stilista del cinema crime contemporaneo, della notte urbana e del digitale puro.',
    style: 'Grana digitale notturna, sound gunshots realistici a presa diretta, solitudine metropolitana.',
    nationality: 'USA',
    birthYear: '1943',
  },
  {
    id: 'hayao-miyazaki',
    name: 'Hayao Miyazaki',
    lastName: 'Miyazaki',
    letter: 'M',
    tmdbId: 608,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'Il demiurgo dello Studio Ghibli e uno dei più grandi artisti visivi di ogni epoca.',
    style: 'Animazione artigianale a mano, ambientalismo mistico, cieli aperti e il concetto di "ma" (vuoto).',
    nationality: 'Giappone',
    birthYear: '1941',
  },

  // N
  {
    id: 'christopher-nolan',
    name: 'Christopher Nolan',
    lastName: 'Nolan',
    letter: 'N',
    tmdbId: 525,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'L\'architetto del tempo non lineare, della pellicola IMAX 70mm e degli effetti pratici monumentali.',
    style: 'Strutture temporali a incastro, pellicola IMAX 70mm, Shepard Tone continuo, zero CGI gratuito.',
    nationality: 'Regno Unito',
    birthYear: '1970',
  },
  {
    id: 'gaspar-noe',
    name: 'Gaspar Noé',
    lastName: 'Noé',
    letter: 'N',
    tmdbId: 4410,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Provocatore radicale del cinema sensoriale estremo, delle luci stroboscopiche e dell\'ipnosi visiva.',
    style: 'Piani sequenza vorticosi aerei, luci al neon pulsanti, frequenze sonore subacquee.',
    nationality: 'Argentina / Francia',
    birthYear: '1963',
  },

  // O
  {
    id: 'yasujiro-ozu',
    name: 'Yasujirō Ozu',
    lastName: 'Ozu',
    letter: 'O',
    tmdbId: 9243,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Il maestro assoluto della serenità geometrica e della vita familiare giapponese.',
    style: 'Tatami shot (inquadratura ad altezza stuoia), inquadrature fisse a 50mm, pillow shots.',
    nationality: 'Giappone',
    birthYear: '1903',
  },

  // P
  {
    id: 'park-chan-wook',
    name: 'Park Chan-wook',
    lastName: 'Park',
    letter: 'P',
    tmdbId: 21683,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Maestro coreano della violenza stilizzata, dell\'erotismo barocco e della vendetta tragica.',
    style: 'Transizioni di montaggio virtuosistiche, carta da parati geometrica, simmetria decadente.',
    nationality: 'Corea del Sud',
    birthYear: '1963',
  },
  {
    id: 'pier-paolo-pasolini',
    name: 'Pier Paolo Pasolini',
    lastName: 'Pasolini',
    letter: 'P',
    tmdbId: 1045,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Poeta, intellettuale e cineasta del sacro, del sottoproletariato e della carne mitologica.',
    style: 'Pittura rinascimentale applicata alla pellicola, attori non professionisti, frontalità sacra.',
    nationality: 'Italia',
    birthYear: '1922',
  },

  // Q
  {
    id: 'brothers-quay',
    name: 'Stephen & Timothy Quay',
    lastName: 'Quay',
    letter: 'Q',
    tmdbId: 102553,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Gemelli maestri della stop-motion esoterica, delle polveri e delle marionette kafkaiane.',
    style: 'Macro-lenti con fuoco millimetrico, marionette decrepite, surrealismo dell\'Europa orientale.',
    nationality: 'USA / UK',
    birthYear: '1947',
  },

  // R
  {
    id: 'nicolas-winding-refn',
    name: 'Nicolas Winding Refn',
    lastName: 'Refn',
    letter: 'R',
    tmdbId: 7247,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'Il profeta dell\'iper-estetica al neon, dell\'ultraviolenza stilizzata e del synthwave noir.',
    style: 'Colori saturi primari (daltonismo), lentezza ieratica, composizioni frontali immobili.',
    nationality: 'Danimarca',
    birthYear: '1970',
  },
  {
    id: 'george-a-romero',
    name: 'George A. Romero',
    lastName: 'Romero',
    letter: 'R',
    tmdbId: 10769,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Il padre dell\'horror zombi moderno e della critica sociale feroce al consumismo americano.',
    style: 'Montaggio serrato documentaristico, gore artigianale di Tom Savini, satira politica.',
    nationality: 'USA',
    birthYear: '1940',
  },

  // S
  {
    id: 'martin-scorsese',
    name: 'Martin Scorsese',
    lastName: 'Scorsese',
    letter: 'S',
    tmdbId: 1032,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'Il gigante supremo del cinema italoamericano, dell\'adrenalina visiva e del montaggio di Thelma Schoonmaker.',
    style: 'Freeze-frame, carrellate veloci, voice-over confessionali, rock\'n\'roll visivo.',
    nationality: 'USA',
    birthYear: '1942',
  },
  {
    id: 'ridley-scott',
    name: 'Ridley Scott',
    lastName: 'Scott',
    letter: 'S',
    tmdbId: 578,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Il demiurgo visivo del cyberpunk futurista e dell\'epica storica maestosa.',
    style: 'Fumo volumetrico, controluce drammatici, multi-camera simultanea, world-building titanico.',
    nationality: 'Regno Unito',
    birthYear: '1937',
  },
  {
    id: 'steven-spielberg',
    name: 'Steven Spielberg',
    lastName: 'Spielberg',
    letter: 'S',
    tmdbId: 488,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Il più influente narratore per immagini dell\'era moderna, padre del blockbuster d\'autore.',
    style: 'Lo "Spielberg Face", composizione in profondità senza stacchi, fasci di luce di Kaminski.',
    nationality: 'USA',
    birthYear: '1946',
  },

  // T
  {
    id: 'quentin-tarantino',
    name: 'Quentin Tarantino',
    lastName: 'Tarantino',
    letter: 'T',
    tmdbId: 138,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Il genio enciclopedico del cinema postmoderno, dei dialoghi mitici e del feticismo 35/70mm.',
    style: 'Trunk shot (inquadratura dal bagagliaio), dialoghi fiume pop, capitoli non lineari, ultraviolenza catartica.',
    nationality: 'USA',
    birthYear: '1963',
  },
  {
    id: 'andrei-tarkovsky',
    name: 'Andrei Tarkovsky',
    lastName: 'Tarkovsky',
    letter: 'T',
    tmdbId: 8452,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Lo scultore del tempo, creatore del cinema più mistico, spirituale e contemplativo mai concepito.',
    style: 'Piani sequenza meditativi, elementi primordiali (acqua/fuoco/terra), dilatazione temporale assoluta.',
    nationality: 'Russia',
    birthYear: '1932',
  },
  {
    id: 'guillermo-del-toro',
    name: 'Guillermo del Toro',
    lastName: 'del Toro',
    letter: 'T',
    tmdbId: 10828,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Il poeta dei mostri gentili, delle fiabe dark e dell\'artigianato fantasy impeccabile.',
    style: 'Palette ambra e blu di Prussia, mostri in trucco prostetico, fiaba gotica e amore per i diversi.',
    nationality: 'Messico',
    birthYear: '1964',
  },

  // U
  {
    id: 'peter-ustinov',
    name: 'Peter Ustinov',
    lastName: 'Ustinov',
    letter: 'U',
    tmdbId: 9814,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Poliedrico drammaturgo, attore e regista di commedie ironiche e drammi d\'epoca.',
    style: 'Eleganza teatrale, ironia aristocratica britannica, messa in scena classica.',
    nationality: 'Regno Unito',
    birthYear: '1921',
  },

  // V
  {
    id: 'denis-villeneuve',
    name: 'Denis Villeneuve',
    lastName: 'Villeneuve',
    letter: 'V',
    tmdbId: 137427,
    photoUrl: 'https://image.tmdb.org/t/p/w500/zvhkg1N3T9w3t3X1a9W9g8bL5Jb.jpg',
    bio: 'Maestro del cinema visivo contemporaneo, scultore della scala e del silenzio monumentale.',
    style: 'Brutalismo geometrico, sound design tellurico, introspezione fantascientifica.',
    nationality: 'Canada',
    birthYear: '1967',
  },
  {
    id: 'agnes-varda',
    name: 'Agnès Varda',
    lastName: 'Varda',
    letter: 'V',
    tmdbId: 11467,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'La nonna della Nouvelle Vague, pioniera della docu-fiction e della libertà dello sguardo.',
    style: 'Cine-scrittura, collage giocoso, empatia sociale e libertà formale assoluta.',
    nationality: 'Francia',
    birthYear: '1928',
  },
  {
    id: 'paul-verhoeven',
    name: 'Paul Verhoeven',
    lastName: 'Verhoeven',
    letter: 'V',
    tmdbId: 783,
    photoUrl: 'https://image.tmdb.org/t/p/w500/b3j62rFmZzF3bH5gQ6p5rK8yX7z.jpg',
    bio: 'Provocatore implacabile, maestro della satira iper-violenta e del thriller erotico sovversivo.',
    style: 'Satira sociale distopica, ultraviolenza corporale, sensualità ambigua e cinismo.',
    nationality: 'Paesi Bassi',
    birthYear: '1938',
  },

  // W
  {
    id: 'wong-kar-wai',
    name: 'Wong Kar-wai',
    lastName: 'Wong',
    letter: 'W',
    tmdbId: 12453,
    photoUrl: 'https://image.tmdb.org/t/p/w500/jdpvQeE91XgH8kYn4hQ0xR2Wz1a.jpg',
    bio: 'Il poeta della memoria, del desiderio inespresso e dei colori al neon di Hong Kong.',
    style: 'Step-printing (fotogrammi duplicati al rallentatore), luci al neon, fumo di sigaretta e tango malinconico.',
    nationality: 'Hong Kong',
    birthYear: '1958',
  },
  {
    id: 'orson-welles',
    name: 'Orson Welles',
    lastName: 'Welles',
    letter: 'W',
    tmdbId: 40,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s3b7k0jG5hV4jZ5Xk1jZ2p7q8r9.jpg',
    bio: 'Il genio che a 25 anni con Quarto Potere ha rivoluzionato per sempre la grammatica del cinema.',
    style: 'Angolazioni dal basso con soffitti visibili, deep focus di Gregg Toland, montaggio radiodrammatico.',
    nationality: 'USA',
    birthYear: '1915',
  },
  {
    id: 'wim-wenders',
    name: 'Wim Wenders',
    lastName: 'Wenders',
    letter: 'W',
    tmdbId: 2303,
    photoUrl: 'https://image.tmdb.org/t/p/w500/a2D2U5u9Z5zG6n4m4g8X6zX5Xk1.jpg',
    bio: 'Il viaggiatore del cinema tedesco, poeta del paesaggio americano e dello sguardo contemplativo.',
    style: 'Road movie esistenziali, colori pastello di Robby Müller, silenzi poetici e architettura urbana.',
    nationality: 'Germania',
    birthYear: '1945',
  },

  // X
  {
    id: 'xie-jin',
    name: 'Xie Jin',
    lastName: 'Xie',
    letter: 'X',
    tmdbId: 110668,
    photoUrl: 'https://image.tmdb.org/t/p/w500/m78n9K0jG5hV4jZ5Xk1jZ2p7q8r.jpg',
    bio: 'Maestro storico del cinema cinese, testimone della transizione culturale e del dramma umano.',
    style: 'Composizione classica rigorosa, grande respiro emotivo, realismo umanista.',
    nationality: 'Cina',
    birthYear: '1923',
  },

  // Y
  {
    id: 'edward-yang',
    name: 'Edward Yang',
    lastName: 'Yang',
    letter: 'Y',
    tmdbId: 46682,
    photoUrl: 'https://image.tmdb.org/t/p/w500/s9mZ1x9Q8jY6k4h2p7m0X3n2w1v.jpg',
    bio: 'Pilastro della New Wave Taiwanese, autore di ritratti metropolitani di infinita delicatezza.',
    style: 'Inquadrature attraverso finestre e riflessi, Taipei contemporanea, profondità emotiva straordinaria.',
    nationality: 'Taiwan',
    birthYear: '1947',
  },
  {
    id: 'zhang-yimou',
    name: 'Zhang Yimou',
    lastName: 'Zhang',
    letter: 'Y',
    tmdbId: 1046,
    photoUrl: 'https://image.tmdb.org/t/p/w500/nbN1y5xJ4X8pG5K9vH4jZ5Xk1jZ.jpg',
    bio: 'Il maestro visivo della Quinta Generazione cinese, scultore del colore e del wuxia estetico.',
    style: 'Colori simbolici monocromatici (rosso/giallo/blu), composizioni coreografiche titaniche.',
    nationality: 'Cina',
    birthYear: '1951',
  },

  // Z
  {
    id: 'robert-zemeckis',
    name: 'Robert Zemeckis',
    lastName: 'Zemeckis',
    letter: 'Z',
    tmdbId: 24,
    photoUrl: 'https://image.tmdb.org/t/p/w500/6y0sN8n5q2J3jV4jY1n7Kz4Z9vA.jpg',
    bio: 'Il pioniere assoluto dell\'interazione tra live-action, animazione e storytelling cinetico.',
    style: 'Movimenti di macchina impossibili in CGI/pratici, ritmo incalzante, meraviglia tecnica.',
    nationality: 'USA',
    birthYear: '1952',
  },
  {
    id: 'chloe-zhao',
    name: 'Chloé Zhao',
    lastName: 'Zhao',
    letter: 'Z',
    tmdbId: 1391363,
    photoUrl: 'https://image.tmdb.org/t/p/w500/y65l709jGkGk0vNq0hVjE5Xk1jZ.jpg',
    bio: 'Vincitrice dell\'Oscar per Nomadland, cantrice dei grandi spazi americani e della verità umana.',
    style: 'Luce naturale crepuscolare, attori non professionisti, intimismo lirico e contemplazione.',
    nationality: 'Cina / USA',
    birthYear: '1982',
  },
];
